export { HeroSection } from './HeroSection';
export { USPSection } from './USPSection';
export { FeaturedProductSection } from './FeaturedProductSection';
export { QivaroSection } from './QivaroSection';
export { WhyChooseUsSection } from './WhyChooseUsSection';
export { GoogleReviewsSection } from './GoogleReviewsSection';
export { ContactTeaserSection } from './ContactTeaserSection';
export { PartnersSection } from './PartnersSection';
export { FAQSection } from './FAQSection';
